# Generated by Django 4.1.3 on 2022-12-02 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 2, 20, 31, 23, 578776)
            ),
        ),
    ]
