# Generated by Django 4.1.3 on 2022-12-05 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transaction_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 5, 21, 58, 43, 967661)
            ),
        ),
    ]
