# Generated by Django 4.1.3 on 2022-12-07 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_transaction_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name="Date and Time of the transaction creation",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 7, 4, 16, 28, 462360),
                verbose_name="Date and Time of the transaction",
            ),
        ),
    ]
